---
title: "hw_4_rmd"
author: "Alyssa Melvin"
date: "October 24, 2018"
output: word_document
---

```{r}
library(readr)
library(dplyr)
library(tidyr) 
library(purrr)
library(broom)
library(ggplot2)
library(forcats)
library(scales)

homicides <- read_csv("../data/homicide-data.csv") 

homicides <- homicides %>% 
  unite(city_name, "city", "state", sep = ", " )

baltimore <- homicides %>% 
  group_by(city_name) %>% 
  filter(city_name == "Baltimore, MD") %>% 
  mutate(unsolved = disposition %in% c("Closed without arrest", 
                                       "Open/No arrest")) %>%
  summarise(total = n(), unsolved = sum(unsolved))
 
baltimore_prop_results <- prop.test(x = baltimore$unsolved, n = baltimore$total)

unsolved <- homicides %>% 
  mutate(unsolved = disposition %in% c("Closed without arrest", 
                                       "Open/No arrest")) %>% 
  select(city_name, unsolved) %>% 
  group_by(city_name) %>% 
  summarise(N = n(), unsolved = sum(unsolved)) %>% 
  mutate(prop_results = map2(.x = unsolved, .y = N, .f = prop.test)) %>% 
  mutate(prop_results = map(.x = prop_results, .f = tidy)) %>% 
  unnest(prop_results, .drop = TRUE)  %>% 
  select(city_name, estimate, conf.low, conf.high) %>% 
  mutate(estimate = 100*estimate,
         conf.low = 100*conf.low,
         conf.high = 100*conf.high)
```

```{r, fig.height=8}
  
  
unsolved %>% 
  mutate(city_name = fct_reorder(city_name, estimate, desc = TRUE)) %>% 
  ggplot() +
  geom_point(aes(x = city_name, y = estimate)) +
  scale_y_continuous(labels = percent) +
  ylim(20, 80) +
  coord_flip() +
  theme_dark() +
  labs(x = "", y = "Percent of homicides that are unsolved") +
  ggtitle("Unsolved homicides by city", subtitle = "Bars show 95% confidence interval")
  
  
  
#geom_errorbarh(aes(x = city_name, y = estimate, xmin = conf.low, xmax = conf.high, height = 0))
```